### ISSUE TITLE
Previous application version is not decommissioned 

### ISSUE THREAD

**Issue by lucimihai** [orachide/ansible-role-springboot#8]
When an existing version of the application is runnning(e.g.: 1.0.0) and new version 1.0..1 is beeing deployed, I would expect the instanvce running the previous version to be stopped and a new instance with the new version to be started.
Actually, I can still see the previous version running after the playbook is run successfully.

**Comment by orachide** [comment]
Hello,
I’ll make a fix for that. I’ll only stop the previous version but not uninstall it.

**Comment by lucimihai** [comment]
Ok. Thanks.

This is also the workaround I have applied.

**Comment by orachide** [comment]
If you already have a fix/workaround could you please submit a pull request ?

**Comment by lucimihai** [comment]
I mean I called a task to stop the service before the role.

**Comment by orachide** [comment]
Hello,

I just checked this issue by changing the version to deploy (different `sb_app_version` and different `sb_app_artifact_file`) and actually the symlink to the previous version change and therefore when the role restart the service (due to symlink changes) the previous version is stop and the new one is started.

Could you please let me know how you have tested that?

By the way i'm assuming the first version you have deployed was deployed using this role.

**Comment by orachide** [comment]
Issue fix now, actually symlink changes were not trigger service restart. it should be Ok now
